### ISSUE TITLE
Feature request: Area for Batch Upload

### ISSUE THREAD

**Issue by d2boy** [afonic/rimage-k2#7]
Enable drag & drop upload by default (Skip Add Images button)
![image](https://user-images.githubusercontent.com/33113853/53178546-7a8b4b00-360b-11e9-8fbf-77f698cbc2de.png)

**Comment by afonic** [comment]
The drag and drop upload cannot work for the "drag to order" so this will create some confusion. It's best to keep it separately for the moment (so that the user is forced to Save & Close) until a better solution is found.
